<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<jsp:include page="/WEB-INF/index/header.jsp" flush="true"></jsp:include>
<body class="easyui-layout" style="background:#d5e1f2">
<div data-options="region:'north',border:'false'" id="publicNorth">
    <div class="search-group" style="float: right;width:180px;margin-right: 50px">
        <li class="query-btn" style="float: right"><a class="icon iconfont icon-icon- " onclick="save()"><i>保存</i></a></li>
    </div>
</div>
<div data-options="region:'center',border:false">
    <div class="h3"></div>
    <div class="tabContainer">
        <div class="tabTitle">
        </div>
        <div class="tabContent">
            <form class='easyui-form' id='form' method='post'>
                <div class="conContent">

                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

<script type="text/javascript">
    $(function(){
        loadContract();
    });
    function loadContract(){
        inserHtml = '<div>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:right; widows:0"><span style="font-family:楷体_GB2312; font-size:18pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:right; widows:0"><span style="font-family:楷体_GB2312; font-size:18pt">徐房租补</span>  <span style="font-family:\'Times New Roman\'; font-size:18pt; text-decoration:underline"> &nbsp;&nbsp;${contractTemplateFillingDataPojo.regionCodeStr }<input type="hidden" name="contractTemplateFillingDataPojo.regionCodeStr" value="${contractTemplateFillingDataPojo.regionCodeStr }"> &nbsp;&nbsp; </span> </span><span style="font-family:楷体_GB2312; font-size:18pt">区〔</span><span style="font-family:楷体_GB2312; font-size:18pt"> ${contractTemplateFillingDataPojo.year }<input type="hidden" name="contractTemplateFillingDataPojo.year" value="${contractTemplateFillingDataPojo.year }">  </span><span style="font-family:楷体_GB2312; font-size:18pt">〕第</span><span style="font-family:楷体_GB2312; font-size:18pt">${contractTemplateFillingDataPojo.htQue  }<input type="hidden" name="contractTemplateFillingDataPojo.htQue" value="${contractTemplateFillingDataPojo.htQue }"><input type="hidden" name="contractTemplateFillingDataPojo.contractNo" value="${contractTemplateFillingDataPojo.contractNo }">  </span><span style="font-family:楷体_GB2312; font-size:18pt"> </span><span style="font-family:楷体_GB2312; font-size:18pt">号</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:方正小标宋简体; font-size:24pt">徐州市市区公共租赁住房租赁</span><span style="font-family:方正小标宋简体; font-size:24pt">补贴协议</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:\'Times New Roman\'; font-size:24pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:楷体_GB2312; font-size:18pt">徐州市住房保障服务中心</span><span style="font-family:楷体_GB2312; font-size:18pt">印</span><span style="font-family:楷体_GB2312; font-size:18pt">制</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:\'Times New Roman\'; font-size:18pt">&#xa0;</span></p>\n' +
            '\t<p style="margin:0pt; orphans:0; widows:0"><span style="font-family:黑体; font-size:15pt">甲方：</span><span style="font-family:仿宋_GB2312; font-size:16pt">徐州市住房保障服务中心</span></p>\n' +
            '\t<p style="margin:7.8pt 0pt 0pt; orphans:0; widows:0"><span style="font-family:黑体; font-size:15pt">乙方：</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> ${contractTemplateFillingDataPojo.userName }<input type="hidden" name="contractTemplateFillingDataPojo.userName" value="${contractTemplateFillingDataPojo.userName }">  </span>\n' +
            '\t\t<a name="userName"><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline"></span><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline">  </span></a><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline"> </span><span style="font-family:\'Times New Roman\'; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">身份证号码：</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline">${contractTemplateFillingDataPojo.userCardId }<input type="hidden" name="contractTemplateFillingDataPojo.userCardId" value="${contractTemplateFillingDataPojo.userCardId }"> </span>\n' +
            '\t\t<a name="userIDCard"><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline">    </span></a><span style="font-family:\'Times New Roman\'; font-size:16pt; text-decoration:underline">      </span></p>\n' +
            '\t<p style="line-height:27pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:15pt">&#xa0;</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第一条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">根据</span><span style="font-family:仿宋_GB2312; font-size:16pt">《徐州市市区廉租住房保障办法》</span><span style="font-family:仿宋_GB2312; font-size:16pt">（徐政规〔</span><span style="font-family:\'Times New Roman\'; font-size:16pt">20</span><span style="font-family:\'Times New Roman\'; font-size:16pt">09</span><span style="font-family:仿宋_GB2312; font-size:16pt">〕</span><span style="font-family:\'Times New Roman\'; font-size:16pt">3</span><span style="font-family:仿宋_GB2312; font-size:16pt">号）</span><span style="font-family:仿宋_GB2312; font-size:16pt">、</span><span style="font-family:仿宋_GB2312; font-size:16pt">《徐州市市区公共租赁住房和廉租住房并轨运行实施细则》（徐政办发〔</span><span style="font-family:\'Times New Roman\'; font-size:16pt">2016</span><span style="font-family:仿宋_GB2312; font-size:16pt">〕</span><span style="font-family:\'Times New Roman\'; font-size:16pt">3</span><span style="font-family:仿宋_GB2312; font-size:16pt">号）等相关规定，乙方自愿、如实申请市区公共租赁住房租赁补贴，经双方协商一致，并经乙方家庭成员全体一致同意，由</span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方代表家庭全体成员与甲方就公共租赁住房租赁补贴相关事宜签订本</span><span style="font-family:仿宋_GB2312; font-size:16pt">协议</span><span style="font-family:仿宋_GB2312; font-size:16pt">。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第二条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">经双方核算，乙方家庭成员</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> ${contractTemplateFillingDataPojo.familyNum }   </span><span style="font-family:仿宋_GB2312; font-size:16pt">人，可享受租赁补贴</span><input class="easyui-textbox" style="width:200px" name="rentalSubsidiesNum" data-options="label:\'\',required:true,validType:\'empty\'"><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">人，家庭现有人均住房建筑面积</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">平方米，人均可享受补贴建筑面积</span>15<span style="font-family:仿宋_GB2312; font-size:16pt">平方米，补贴发放标准</span><span style="font-family:仿宋_GB2312; font-size:16pt"><input class="easyui-textbox" style="width:200px" name="rentalSubsidiesUP" data-options="label:\'\',required:true,validType:\'empty\'">元</span><span style="font-family:\'Times New Roman\'; font-size:16pt">∕</span><span style="font-family:仿宋_GB2312; font-size:16pt">平方米，每月租赁补贴金额共计</span><span style="font-family:仿宋_GB2312; font-size:16pt;"><input class="easyui-textbox" style="width:200px" name="rentalSubsidiesTP" data-options="label:\'\',required:true,validType:\'empty\'">元<span></span>（大写</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">      </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">   </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">     </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">）。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第三条</span><span style="font-family:黑体; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">甲方自</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">年</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">月</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">日起至</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">     </span><span style="font-family:仿宋_GB2312; font-size:16pt">年</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">月</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">日止，按月并在每月</span><span style="font-family:25  </span><span style="font-family:仿宋_GB2312; font-size:16pt">日前，将租赁补贴转入乙方提供的银行账户。乙方提供的账户名称为：</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> ${contractTemplateFillingDataPojo.accountTitle }<input type="hidden" name="contractTemplateFillingDataPojo.accountTitle" value="${contractTemplateFillingDataPojo.accountTitle }"> </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">，银行账号</span><span style="font-family:仿宋_GB2312; font-size:16pt">为：</span><input class="easyui-textbox" style="width:200px" name="bankAccount" data-options="label:\'\',required:true,validType:\'empty\'"></span><span style="font-family:仿宋_GB2312; font-size:16pt">。该账号发生变化时，乙方应及时书面通知甲方，否则，未能按时领取租赁补贴的责任由其自行承担。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; text-indent:21.75pt; widows:0"><span style="font-family:黑体; font-size:16pt">第四条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">住房租赁补贴只能用于冲减乙方家庭租住的房屋租金。</span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方有住房但未达到</span><span style="font-family:仿宋_GB2312; font-size:16pt">人均住房保障标准</span><span style="font-family:仿宋_GB2312; font-size:16pt">的，由甲方按核算后的金额发放租赁补贴。</span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方</span><span style="font-family:仿宋_GB2312; font-size:16pt">无住房的，</span><span style="font-family:仿宋_GB2312; font-size:16pt">自行到市场上租赁住房解决住房困难，在</span><span style="font-family:仿宋_GB2312; font-size:16pt">签订本协议</span><span style="font-family:仿宋_GB2312; font-size:16pt">之前须</span><span style="font-family:仿宋_GB2312; font-size:16pt">将与他方所订立的房屋租赁协议</span><span style="font-family:仿宋_GB2312; font-size:16pt">备案</span><span style="font-family:仿宋_GB2312; font-size:16pt">后</span><span style="font-family:仿宋_GB2312; font-size:16pt">报甲方。</span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方与他方订立租金标准低于补贴</span><span style="font-family:仿宋_GB2312; font-size:16pt">标准</span><span style="font-family:仿宋_GB2312; font-size:16pt">的，甲方按</span><span style="font-family:仿宋_GB2312; font-size:16pt">房屋租金标准</span><span style="font-family:仿宋_GB2312; font-size:16pt">发放补贴；高于补贴标准的，超过部份由乙方自理。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第五条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">租赁补贴实行年度审核制度。乙方须在本协议期满前</span><span style="font-family:\'Times New Roman\'; font-size:16pt">30</span><span style="font-family:仿宋_GB2312; font-size:16pt">天</span><span style="font-family:仿宋_GB2312; font-size:16pt">内</span><span style="font-family:仿宋_GB2312; font-size:16pt">向甲方申请办理年度审核。乙方未及时申请办理年度审核造成的租赁补贴发放有误的，由乙方承担责任。逾期</span><span style="font-family:仿宋_GB2312; font-size:16pt">未办理</span><span style="font-family:仿宋_GB2312; font-size:16pt">的，甲方停止发放租赁补贴。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第六条</span><span style="font-family:黑体; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方补报审核材料的，经甲方审</span><span style="font-family:仿宋_GB2312; font-size:16pt">核符合租赁补贴条件的，自次月起恢复发放租房补贴，但停发期间的租赁</span><span style="font-family:仿宋_GB2312; font-size:16pt">补贴不予补发。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第七条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">甲方应按本协议规定，按时并足额发放租赁补贴，如果甲方未按规定履行本协议，则乙方可要求甲方按协议履行。乙方应依法、诚信申报，保证向甲方提供的材料真实有效，否则，由乙方承担违约责任。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第八条</span><span style="font-family:仿宋_GB2312; font-size:16pt">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方必须将补贴用于租房。如有下列情况之一，甲方将停发租赁</span><span style="font-family:仿宋_GB2312; font-size:16pt">补贴和提前终止协议，并依法予以处罚、记入个人征信系统和公示。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（一）乙方家庭的人均收入、住房等情况发生变化不再符合保障标准的；</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（二）虚报、隐瞒有关情况或者伪造有关证明；</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（三）将租赁</span><span style="font-family:仿宋_GB2312; font-size:16pt">补贴挪作他用或将承租房屋转借、转租的；</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（四）领取租赁补贴后，连续六个月内不在租赁房屋居住的；</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（五）不按规定，接受住房保障部门审核和复审的；</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">（六）违反市区公共租赁住房管理相关规定的。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">违反</span><span style="font-family:仿宋_GB2312; font-size:16pt">（二）、（三）、（四）规定的，停发租赁补贴的同时，收回已发放租赁</span><span style="font-family:仿宋_GB2312; font-size:16pt">补贴。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第九条</span><span style="font-family:黑体; font-size:16pt"> </span><span style="font-family:黑体; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方在本协议中填写的本人姓名、联系方式、证件信息以及提供的银行卡号须准确无误、真实有效。联系方式如有变更，乙方应书面通知甲方。</span><span style="font-family:仿宋_GB2312; font-size:16pt">如乙方联系方式等信息发生变化未及时告知甲方而影响租赁补贴发放的，由乙方承担全部责任。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第十条  </span><span style="font-family:仿宋_GB2312; font-size:16pt">本协议履行过程中发生争议时，双方应协商解决；协商不成的，可依法向人民法院提起诉讼。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; text-indent:21pt; widows:0"><span style="font-family:黑体; font-size:16pt">第十</span><span style="font-family:黑体; font-size:16pt">一</span><span style="font-family:黑体; font-size:16pt">条</span><span style="font-family:黑体; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt"> </span><span style="font-family:仿宋_GB2312; font-size:16pt">本协议经甲乙双方签字盖章后生效。本协议一式贰份，甲、乙双方各执壹份，具有同等法律效力。</span></p>\n' +
            '\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; text-indent:21pt; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">&#xa0;</span></p>\n' +
            '\t<div style="margin-left: 37%;">\n' +
            '\t\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">甲方（签章）：</span><span style="font-family:仿宋_GB2312; font-size:16pt">                     </span><span style="font-family:仿宋_GB2312; font-size:16pt">乙方（签字）：</span></p>\n' +
            '\t\t<p style="line-height:30pt; margin:7.8pt 0pt 0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">经办人：</span><span style="font-family:仿宋_GB2312; font-size:16pt">                          </span><span style="font-family:仿宋_GB2312; font-size:16pt">联系电话：</span></p>\n' +
            '\t\t<p style="line-height:30pt; margin:7.8pt 0pt 0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">联系电话：</span><span style="font-family:仿宋_GB2312; font-size:16pt">                        </span><span style="font-family:仿宋_GB2312; font-size:16pt">联系地址：</span></p>\n' +
            '\t\t<p style="line-height:30pt; margin:7.8pt 0pt 0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt">联系地址：</span></p>\n' +
            '\t\t<p style="line-height:30pt; margin:7.8pt 0pt 0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">     </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">     </span><span style="font-family:仿宋_GB2312; font-size:16pt">年</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt">月</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt">日</span><span style="font-family:仿宋_GB2312; font-size:16pt">        </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">   </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline"> </span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">  </span><span style="font-family:仿宋_GB2312; font-size:16pt">年</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt">月</span><span style="font-family:仿宋_GB2312; font-size:16pt; text-decoration:underline">    </span><span style="font-family:仿宋_GB2312; font-size:16pt">日</span></p>\n' +
            '\t\t<p style="line-height:30pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:Calibri; font-size:16pt">&#xa0;</span></p>\n' +
            '\t</div>\n' +
            '</div>';
        $(".conContent").append(inserHtml);
        $.parser.parse($(".conContent"));
    }
    //保存合同
    function save(){
        var data =bank.biography().getParams('butie');
        var id = data.row.appid;
        var type = "${apSqlb}";
        bank.ajaxForm('#form','<%=basePath%>contractTemplate/getContractTemplateFile',
            {objId:id,apSqlb:type},function(data){
            //提交表单
            bank.ajaxMessage(data)
        });
    }
</script>



